version: "3.8"

services:
  simpleapi:
    build:
      context: .
      dockerfile: simpleapi.Dockerfile
    ports:
      - 5000:5000
    environment:
      - API_HOST=${API_HOST}
      - API_PORT=${API_PORT}
      - PYTHONUNBUFFERED=1
    healthcheck:
      test: ["CMD", "curl", "-XGET", "localhost:5000/health"]
      interval: 5s
      timeout: 1s
      retries: 10
      start_period: 10s
  socketexperiment:
    image: python:3.10.4
    environment:
      - API_HOST=${API_HOST}
      - API_PORT=${API_PORT}
      - DEBUG=${DEBUG}
      - PYTHONUNBUFFERED=1
    volumes:
      - ./__init__.py:/__init__.py
      - ./timer.py:/timer.py
      - ./socketexperiment.py:/socketexperiment.py

    entrypoint: ["python3", "-u", "/socketexperiment.py"]
    depends_on:
      simpleapi:
        condition: service_healthy
