version: "3.8"

services:
  simpleapi:
    image: python:3.10.4
    ports:
      - 5000:5000
    environment:
      - API_HOST=${API_HOST}
      - API_PORT=${API_PORT}
  socketexperiment:
    image: python:3.10.4
    environment:
      - API_HOST=${API_HOST}
      - API_PORT=${API_PORT}


