version: "3.8"

services:
  database:
    image: postgres:12
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - database-volume:/var/lib/postgresql
  streamer:
    build:
      context: .
      dockerfile: python.Dockerfile
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - MESSAGES_QUEUE=${MESSAGES_QUEUE}
      - RABBITMQ_HOST=${MESSAGES_HOSTNAME}
    volumes:
      - type: bind
        source: ./src/
        target: /src/
  queueing:
    build:
      context: .
      dockerfile: rabbitmq.Dockerfile
    hostname: ${MESSAGES_HOSTNAME}
    ports:
      - "5672:5672" # Service
      - "15672:15672" # Web interface
    volumes:
      # Persist rabbitmq data
      - rabbit-data:/var/lib/rabbitmq/mnesia/

volumes:
  database-volume:
  rabbit-data:
